nodes:
  - {id: 0, x: 1.0, y: 0.75}
  - {id: 1, x: 1.0, y: 2.25}
  - {id: 2, x: 3.0, y: 0.75}
  - {id: 3, x: 3.0, y: 2.25}
  - {id: 4, x: 5.0, y: 0.75}
  - {id: 5, x: 5.0, y: 2.25}

edges:
  - {from: 0, to: 2}
  - {from: 2, to: 4}
  - {from: 1, to: 3}
  - {from: 3, to: 5}
  - {from: 0, to: 1}
  - {from: 2, to: 3}
  - {from: 4, to: 5}
