services:
  web-ui:
    build:
      context: ../../web-ui
      dockerfile: ../docker/web-ui/Dockerfile
    image: pathfinder-web-ui
    container_name: pathfinder-web-ui
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../../web-ui:/app
      - web-ui-node-modules:/app/node_modules
    command: npm run dev

volumes:
  web-ui-node-modules:
