nodes:
  - {id: 1, x: 0.00, y: 1.57}
  - {id: 2, x: 0.92, y: 1.57}
  - {id: 3, x: 1.94, y: 1.57}
  - {id: 4, x: 0.00, y: 2.78}
  - {id: 5, x: 0.92, y: 2.78}
  - {id: 6, x: 1.94, y: 2.78}
  - {id: 7, x: 0.00, y: 4.56}
  - {id: 8, x: 0.92, y: 4.56}
  - {id: 9, x: 1.94, y: 4.56}

edges:
  - {from: 1, to: 2}
  - {from: 2, to: 3}
  - {from: 1, to: 4}
  - {from: 2, to: 5}
  - {from: 4, to: 5}
  - {from: 3, to: 6}
  - {from: 5, to: 6}
  - {from: 4, to: 7}
  - {from: 5, to: 8}
  - {from: 7, to: 8}
  - {from: 8, to: 9}
  - {from: 6, to: 9}

stations:
  - {node: 6, orientation: 180}
  - {node: 3, orientation: 180}
  - {node: 1, orientation: 0}
  - {node: 9, orientation: 180}
  - {node: 7, orientation: 0}
  - {node: 4, orientation: 0}
