robots:
  - id: tb3_01
    start_node: 9
    yaw: 0.0  # degrees
    motion:
      linear_speed: 0.22
      angular_speed: 1.5
      move_rate_hz: 5.0
      arrival_tolerance: 0.05
    obstacle:
      enabled: true
      stop_distance: 0.4
      detect_degree: 50
  - id: tb3_05
    start_node: 3
    yaw: 0  # degrees
    motion:
      linear_speed: 0.22
      angular_speed: 1.5
      move_rate_hz: 5.0
      arrival_tolerance: 0.05
    obstacle:
      enabled: true
      stop_distance: 0.4
      detect_degree: 50
