robots:
  - id: tb3_01
    name: Robot 1
    start_station: 3
    motion:
      linear_speed: 0.22
      angular_speed: 1.3
      move_rate_hz: 15
      arrival_tolerance: 0.06
      turning_tolerance: 0.10
    obstacle:
      enabled: true
      stop_distance: 0.45
      detect_degree: 45
  - id: tb3_05
    name: Robot 2
    start_station: 5
    motion:
      linear_speed: 0.22
      angular_speed: 1.3
      move_rate_hz: 15
      arrival_tolerance: 0.06
      turning_tolerance: 0.10
    obstacle:
      enabled: true
      stop_distance: 0.45
      detect_degree: 45
