#!/usr/bin/env python3
from typing import cast
import rospy
from pathfinder.ros.path_server_node import PathServerNode
from pathfinder.world.graph import Graph
from pathfinder.world.robot import Robot


def main():
    rospy.init_node('path_server')
    graph_file = cast(str, rospy.get_param('~graph_file'))
    sim = cast(bool, rospy.get_param('~sim', False))
    robots = [Robot.from_dict(r) for r in cast(list, rospy.get_param('~robots'))]

    PathServerNode(Graph.load_from_yaml(graph_file), robots, sim).start()
    rospy.spin()


if __name__ == '__main__':
    main()
