#!/usr/bin/env python3
import math
from typing import List, cast

import rospy

from pathfinder.robot.motion_engine import MotionParameters
from pathfinder.ros.turtlebot_node import TurtleBotNode
from pathfinder.world.graph import Graph
from pathfinder.world.robot import Robot
from geometry_msgs.msg import Pose2D


def main():
    rospy.init_node('robot_executors')
    graph_file = cast(str, rospy.get_param('~graph_file'))
    sim = cast(bool, rospy.get_param('~sim', False))
    robots = [Robot.from_dict(r, sim=sim) for r in cast(list, rospy.get_param('~robots'))]

    graph = Graph.load_from_yaml(graph_file)
    nodes: List[TurtleBotNode] = []

    for robot in robots:
        origin = None
        if not sim:
            start_node = graph.get_node(robot.start_node)
            origin = Pose2D()
            origin.x = start_node.x
            origin.y = start_node.y
            origin.theta = math.radians(robot.yaw)

        params = MotionParameters(
            linear_speed=robot.motion.linear_speed,
            angular_speed=robot.motion.angular_speed,
            arrival_tolerance=robot.motion.arrival_tolerance,
        )
        node = TurtleBotNode(
            robot.id,
            graph=graph,
            namespace=robot.namespace,
            params=params,
            motion_rate_hz=robot.motion.move_rate_hz,
            origin=origin,
            obstacle_enabled=robot.obstacle.enabled,
            obstacle_stop_distance=robot.obstacle.stop_distance,
            obstacle_detect_degree=robot.obstacle.detect_degree,
        )
        node.start()
        nodes.append(node)

    rospy.loginfo(f"Started {len(nodes)} robot executors.")
    rospy.spin()


if __name__ == '__main__':
    main()
