#!/usr/bin/env python3
import math
from typing import List, cast

import rospy

from pathfinder.robot.motion_controller import MotionParameters
from pathfinder.ros.turtlebot_node import TurtleBotNode
from pathfinder.world.graph import Graph
from pathfinder.safety.obstacle_gate import ObstacleGate
from geometry_msgs.msg import Pose2D


def main():
    rospy.init_node('robot_executors')
    graph_file = cast(str, rospy.get_param('~graph_file'))
    linear_speed = cast(float, rospy.get_param('~linear_speed', 0.22))
    angular_speed = cast(float, rospy.get_param('~angular_speed', 1.5))
    motion_rate_hz = cast(float, rospy.get_param('~motion_rate_hz', 5.0))
    obstacle_pause_enabled = cast(bool, rospy.get_param('~obstacle_pause_enabled', True))
    obstacle_stop_distance = cast(float, rospy.get_param('~obstacle_stop_distance', 0.20))
    lidar_error_margin = cast(float, rospy.get_param('~lidar_error_margin', 0.05))
    scan_stale_timeout_seconds = cast(float, rospy.get_param('~scan_stale_timeout_seconds', 1.0))
    sim = cast(bool, rospy.get_param('~sim', False))
    robots = cast(list, rospy.get_param('~robots'))

    graph = Graph.load_from_yaml(graph_file)
    params = MotionParameters(linear_speed=linear_speed, angular_speed=angular_speed)
    nodes: List[TurtleBotNode] = []

    for robot_cfg in robots:
        robot_id = robot_cfg['id']
        origin = None
        if not sim:
            start_node = graph.get_node(robot_cfg['start_node'])
            origin = Pose2D()
            origin.x = start_node.x
            origin.y = start_node.y
            origin.theta = math.radians(float(robot_cfg['yaw']))

        topic_namespace = f'{robot_id}/sim' if sim else robot_id
        gate = ObstacleGate(
            stop_distance=obstacle_stop_distance,
            error_margin=lidar_error_margin,
            stale_timeout_seconds=scan_stale_timeout_seconds,
            cone_half_width_radian=math.radians(10.0),
            time_provider=rospy.get_time,
        ) if obstacle_pause_enabled else None
        node = TurtleBotNode(
            robot_id,
            graph=graph,
            namespace=topic_namespace,
            params=params,
            motion_rate_hz=motion_rate_hz,
            origin=origin,
            obstacle_gate=gate,
        )
        node.start()
        nodes.append(node)

    rospy.loginfo(f"Started {len(nodes)} robot executors.")
    rospy.spin()


if __name__ == '__main__':
    main()
