#!/usr/bin/env python3
from typing import cast
import rospy
from pathfinding_system.world.graph import Graph
from pathfinding_system.robot.motion_controller import MotionParameters
from pathfinding_system.robot.turtlebot_node import TurtleBotNode


def main():
    rospy.init_node('executor')
    robot_id = cast(str, rospy.get_param('~robot_id'))
    topic_namespace = cast(str, rospy.get_param('~topic_namespace', robot_id))
    graph_file = cast(str, rospy.get_param('~graph_file'))
    linear_speed = cast(float, rospy.get_param('~linear_speed', 0.22))
    angular_speed = cast(float, rospy.get_param('~angular_speed', 1.5))
    motion_rate_hz = cast(float, rospy.get_param('~motion_rate_hz', 5.0))

    graph = Graph.load_from_yaml(graph_file)
    turtlebot_node = TurtleBotNode(
        robot_id,
        graph=graph,
        namespace=topic_namespace,
        params=MotionParameters(linear_speed=linear_speed, angular_speed=angular_speed),
        motion_rate_hz=motion_rate_hz,
    )
    turtlebot_node.start()
    rospy.spin()


if __name__ == '__main__':
    main()
