#!/usr/bin/env python3
from typing import List, cast

import rospy

from pathfinding_system.robot.motion_controller import MotionParameters
from pathfinding_system.ros.turtlebot_node import TurtleBotNode
from pathfinding_system.world.graph import Graph
from geometry_msgs.msg import Pose2D


def main():
    rospy.init_node('robot_executors')
    graph_file = cast(str, rospy.get_param('~graph_file'))
    linear_speed = cast(float, rospy.get_param('~linear_speed', 0.22))
    angular_speed = cast(float, rospy.get_param('~angular_speed', 1.5))
    motion_rate_hz = cast(float, rospy.get_param('~motion_rate_hz', 5.0))
    sim = cast(bool, rospy.get_param('~sim', False))
    robots = cast(list, rospy.get_param('~robots'))

    graph = Graph.load_from_yaml(graph_file)
    params = MotionParameters(linear_speed=linear_speed, angular_speed=angular_speed)
    nodes: List[TurtleBotNode] = []

    for robot_cfg in robots:
        robot_id = robot_cfg['id']
        origin = None
        if not sim:
            o = robot_cfg.get('origin', {})
            origin = Pose2D()
            origin.x = o.get('x', 0.0)
            origin.y = o.get('y', 0.0)
            origin.theta = o.get('theta', 0.0)

        topic_namespace = f'{robot_id}/sim' if sim else robot_id
        node = TurtleBotNode(
            robot_id,
            graph=graph,
            namespace=topic_namespace,
            params=params,
            motion_rate_hz=motion_rate_hz,
            origin=origin
        )
        node.start()
        nodes.append(node)

    rospy.loginfo(f"Started {len(nodes)} robot executors.")
    rospy.spin()


if __name__ == '__main__':
    main()
