#!/usr/bin/env python3
import rospy
from pathfinding_system.simulation.gazebo_control import unpause_gazebo


def main():
    rospy.init_node('unpause_gazebo')
    unpause_gazebo()
    rospy.loginfo("Gazebo physics unpaused.")


if __name__ == '__main__':
    main()
