#!/usr/bin/env python3
import sys
import rospy
from pathfinding_system.client.user_client import USER_COMMANDS, UserClient


USAGE = (
    "Usage: rosrun pathfinding_system user_client <robot_id> "
    "<target_node_id|stop|turn_left degrees|turn_right degrees|move_forward meters|move_backward meters>"
)


def main():
    if len(sys.argv) < 3:
        print(USAGE)
        sys.exit(1)
    robot_id = sys.argv[1]
    rospy.init_node('user_client', anonymous=True)
    client = UserClient()
    if sys.argv[2] == 'stop':
        if len(sys.argv) != 3:
            print(USAGE)
            sys.exit(1)
        client.cancel(robot_id)
    elif sys.argv[2] in USER_COMMANDS:
        if len(sys.argv) != 4:
            print(USAGE)
            sys.exit(1)
        try:
            value = float(sys.argv[3])
        except ValueError:
            print(USAGE)
            sys.exit(1)
        ok = client.send_command(robot_id, sys.argv[2], value)
        sys.exit(0 if ok else 1)
    else:
        if len(sys.argv) != 3:
            print(USAGE)
            sys.exit(1)
        try:
            target_node_id = int(sys.argv[2])
        except ValueError:
            print(USAGE)
            sys.exit(1)
        ok = client.send_goal(robot_id, target_node_id)
        sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
